name: Attach Custom Connector as release asset

on:
  release:
    types: [published]

jobs:
  build-and-attach:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up MSBuild
      uses: microsoft/setup-msbuild@v1

    - name: Build .mez file
      run: |
        msbuild enlyze.pq.proj /p:Configuration=Release

    - name: Upload `.mez` as release asset
      uses: softprops/action-gh-release@v1
      with:
        files: bin/AnyCPU/Release/enlyze-powerbi.mez
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
